tutorial/blog/urls.py
from django.conf.urls import url
from django.views.generic import ListView, DateDetailView

from blog.models import Post


app_name = 'blog'


urlpatterns = [
    url(r'^$', ListView.as_view(model=Post, paginate_by=3), name='post-list'),
    url(r'^(?P<year>\d{4})/(?P<month>\w{3})/(?P<day>\d{2})/(?P<slug>[-\w]+)/$',
        DateDetailView.as_view(date_field="publish", model=Post),
        name='post-detail')
]

tutorial/tutorial/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog


urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'blog/', include('blog.urls', namespace='blog')),
    path(r'comments/', include('django_comments_xtd.urls')),
    path(r'', TemplateView.as_view(template_name="home.html"),
        name='homepage'),
    path(r'jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]


if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

tutorial/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from django_comments.moderation import CommentModerator
from django_comments_xtd.moderation import moderator, SpamModerator

from blog.badwords import badwords


class PublicManager(models.Manager):
    def get_queryset(self):
        return super(PublicManager, self).get_queryset()\
                                         .filter(publish__lte=timezone.now())


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    allow_comments = models.BooleanField('allow comments', default=True)
    publish = models.DateTimeField(default=timezone.now)
    objects = PublicManager()  # Our custom manager.

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       kwargs={'year': self.publish.year,
                               'month': self.publish.strftime('%b'),
                               'day': self.publish.strftime('%d'),
                               'slug': self.slug})


class PostCommentModerator(SpamModerator):
    email_notification = True
    removal_suggestion_notification = True

    def moderate(self, comment, content_object, request):
        # Make a dictionary where the keys are the words and the message and
        # the values are their relative position in the message.
        def clean(word):
            ret = word
            if word.startswith('.') or word.startswith(','):
                ret = word[1:]
            if word.endswith('.') or word.endswith(','):
                ret = word[:-1]
            return ret

        lowcase_comment = comment.comment.lower()
        msg = dict([(clean(w), i)
                    for i, w in enumerate(lowcase_comment.split())])
        for badword in badwords:
            if isinstance(badword, str):
                if lowcase_comment.find(badword) > -1:
                    return True
            else:
                lastindex = -1
                for subword in badword:
                    if subword in msg:
                        if lastindex > -1:
                            if msg[subword] == (lastindex + 1):
                                lastindex = msg[subword]
                        else:
                            lastindex = msg[subword]
                    else:
                        break
                if msg.get(badword[-1]) and msg[badword[-1]] == lastindex:
                    return True
        return super(PostCommentModerator, self).moderate(comment,
                                                          content_object,
                                                          request)

moderator.register(Post, PostCommentModerator)

tutorial/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html dir="ltr" lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}django-comments-xtd tutorial{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
      .container {
        width: auto;
        max-width: 680px;
        padding: 0 15px;
      }
      .post-footer, .comments {
        padding: 20px 0;
      }
    </style>    
  </head>
  <body>
    <div class="container">
      <div class="page-header">
	    <h4 class="text-center">django-comments-xtd</h4>
	    <h4 class="text-center">{% block header %}{% endblock %}</h4>
      </div>
    </div>

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-12 col-md-12">
          <hr/>
          <p class="text-center text-muted small">django-comments-xtd tutorial.</p>
        </div>
      </div>
    </div>

    {% block extra-js %}
    {% endblock %}
  </body>
</html>

tutorial/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load comments %}
{% load comments_xtd %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}
<h3 class="page-header text-center">{{ object.title }}</h3>
<p class="small text-center">{{ object.publish|date:"l, j F Y" }}</p>
<p>
    {{ object.body|linebreaks }}
</p>

{% get_comment_count for object as comment_count %}
<div class="text-center" style="padding-top:20px">
    <a href="{% url 'blog:post-list' %}">Back to the post list</a>
</div>

<div id="comments"></div>
{% endblock %}

{% block extra-js %}
<script>
 window.comments_props = {% get_commentbox_props for object %};
 window.comments_props_override = {
     allow_comments: {%if object.allow_comments%}true{%else%}false{%endif%},
     allow_feedback: true,
     show_feedback: true,
     allow_flagging: true,
     polling_interval: 5000  // In milliseconds.
 };
</script>
<script src="https://code.jquery.com/jquery-2.2.4.min.js"
        integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
<script type="text/javascript"
        src="{% url 'javascript-catalog' %}"></script>
<script src="{% static 'django_comments_xtd/js/vendor-2.1.0.js' %}"></script>
<script src="{% static 'django_comments_xtd/js/plugin-2.1.0.js' %}"></script> 
<script>
 $(function () {
     $('[data-toggle="tooltip"]').tooltip({html: true})
 })</script>
{% endblock %}

tutorial/templates/blog/post_list.html
{% extends "base.html" %}
{% load comments %}

{% block content %}
<h3 class="page-header text-center">Blog</h3>

{% for object in object_list %}
<h4>
    <a href="{{ object.get_absolute_url }}">
        {{ object.title }}
    </a>
</h4>
<p class="date">
    {% get_comment_count for object as comment_count %}
    Published {{ object.publish }}
    {% if comment_count %}
    &sdot;&nbsp;{{ comment_count }} comments
    {% endif %}
</p>
{{ object.body|truncatewords:30|linebreaks }}
{% endfor %}

<div class="text-center">
    <ul class="pagination pagination-sm">
        {% if page_obj.has_previous %}
        <li>
	        <a href="{% url 'blog:post-list' %}?page={{ page_obj.previous_page_number }}">previous</a>
        </li>
        {% endif %}
        {% if page_obj.has_next %}
        <li>
	        <a href="{% url 'blog:post-list' %}?page={{ page_obj.next_page_number }}">next</a>
        </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

tutorial/templates/comments/400-debug.html
{% extends "base.html" %}

{% block title %}Bad request{% endblock %}

{% block content %}
<h3 class="text-center">Comment post not allowed</h3>
<p class="text-center">{{ why }}</p>
<hr/>
<p class="col-lg-offset-1 col-md-offset-1 text-muted">
  You're seeing this error because you have <code>DEBUG = True</code> in
  your Django settings file. Change that to <code>False</code>, and Django
  will display a standard 400 error page.
</p>
{% endblock %}

tutorial/templates/home.html
{% extends "base.html" %}

{% block content %}
<h3 class="page-header text-center">tutorial</h3>
<p>Contains a simple <code>blog</code> application with a <code>Post</code> model to which we will add comments by using <strong>django-contrib-comments</strong> and <strong>django-comments-xtd</strong>.</p>
<p>Continue to the <a href="{% url 'blog:post-list' %}">blog</a>.</p>
{% endblock %}

tutorial/templates/includes/django_comments_xtd/comment_content.html
{% load md2 %}
{{ content|markdown:"safe, code-friendly, code-color" }}